language: groovy
jdk:
  - openjdk8
env:
  matrix:
   - LIB_GRADLE_VERSION=3.4.1 DEPLOY=true
   - LIB_GRADLE_VERSION=3.5.1
   - LIB_GRADLE_VERSION=4.0.1
   - LIB_GRADLE_VERSION=4.1
   - LIB_GRADLE_VERSION=4.2 DEPLOY=true
   - LIB_GRADLE_VERSION=4.2.1
   - LIB_GRADLE_VERSION=4.5 DEPLOY=true
   - LIB_GRADLE_VERSION=4.5.1
   - LIB_GRADLE_VERSION=4.8 DEPLOY=true
   - LIB_GRADLE_VERSION=4.8.1
   - LIB_GRADLE_VERSION=4.10.2
   - LIB_GRADLE_VERSION=7.2 DEPLOY=true
  global:
    # The next declaration is the encrypted gradlePublishKey
    - secure: tzRoJbjW38G0YcSRuf53+koo/ZixIrA1vHJ9StOfafZOJzKyoASkbFa2EpUKmp3CXBWvUSTVo59j7ywUSyWW+L+G+CRnYqkDTktySJ/LAHjR0CH5dJCUodwcwtZkBje/RQZ//ZuPO2I7wY/aqHfj/E8pg2h9Y+nOd2v9R904/5b5gck9nM1Tr74YE2dJDm3h0QKrMqx6/oT7KVTWQpTNeLxcdrdNn5yxllqn4YDF70gEksoSuJeFR2l5lwSlTTseKI7Q7mGYI1Tg/PSZoxlPz3DGFmSe+9sewRnN9ZnjQDEY06/GmrGQHGv9MV1azvenlFHrt9lIbHnEo0GBqxNpeFfMd4+B9oeEmL8roapNSq0TCgVvOzda/G5KyY8TgLEi+k7WrZaWGvbW+AorU5ntenWEzSWz3b5lpwnwXxrPyyRnaKd3R5mRYj+LL10hlHAiWpvXn+v6ptD2OunE6l3JEm+wln+6wZjJBqBhl1jsv3LOd5siezFGqqOzC6FN6UgkTZqsgMfROzoqklFv3Ko8fU4e6oo9VzI/cJGcFHFO4M+dOHyYZbKl8hfvi1Bf44UpYo914sdwmWGIAZ8J6V2xtCqTnyN1bi/EQuKAkE2400laduCt/rnGyR8IefcM6iFxjufR5jCXpXBhbQ0cQ//pUT0eW4ssjqKvt9RrJmt/Mew=
    # The next declaration is the encrypted gradlePublishSecret
    - secure: Z9rf5KL9USpw7n05xJ+6hLSxgwgepXEw+f5ZwUx9cqKr/TdjSHimjHaGrYizBjjqXxa5fXwoAXmh8dvxyp0khKvtRrhN9JU2WRJt/Kweu/hrW5F+EkrzGBIeDoAtQvLqwOVQH5usRxVBHz3OEcwiFZKldcnvpMaCJcPVpO3YGfDVoX9+dlRYJRAPYFH0LsxJFiZYFzDN3x+eeVfnucgwXkRco+8R04gJ/LGF4rQhn6FupQWk8AepvnmAhAg1HhEvWUSwmD/sQ86xHw9WqMX/PxdSb21tM8VYrj6+ZGFh8C1g7NAVkOSFQjjYSqHb1wDUBHmxMvyUw3KZiBkhFjweTpuxoPHVwbQqhFKH/WXYtnuYKoIlebR7c7CtZ11Xp9ba98PA3ADIzRvOQrPn42iyvXvqg78AROb2OtOa639znxu3lckDoU3PH/n5jHmy9awlwEZSoNkw0dM+RtJGO+X4l1kPQGoOMZVjlA/vvkfhHJqCOwZHX8O9bW/yv328jmgRMdTo8uTV9IrzqgJJgg+v7iEJ1DpBph46dFn7zPliUQWXDDCxXqXSy9V1BVFB1fTKzP9fosrbCCu3CjaTdiXBdPvKpjLE+gVJRt12rzQOKAzOcIt5GtJIkkElo2v3ofSJPdx9aET/nYJepiKW5NMxoPkq/HsMRbeQiyEs3WXqaCQ=
before_install:
  - echo $TRAVIS_TAG
  - sudo apt-get -qq update
  - sudo apt-get install -y fakeroot
install:
  - gradle wrapper
  # upload to '../repo'
  - ./gradlew publish
deploy:
  provider: releases
  api_key:
    secure: "K/aJ9EVz4zpT8uluF1tllJfk1BdlKN3fhyMbygkBtBk979yCKJ+vc+yoUWeu2RGl36IAcj7o/mJQFaLF2yaZ1vzX5/exTasIjCOkDOquC2IozaS5Tji2DZumzOEchy/F/apHmqqFnluYF4jX4q74RTI4bzYJhuy8/MvXJ5nCag3GqrjovA0CRTIXz1q5RoTdbtwN2CFwQk0iVbc2AgoRSnZDV2M9OiKezdGYr7tGogvhB0bVJ4VWW81D116dhM20JS7M4A8GIt6BCpaXy3kKdBSBvrxTawAeR7WJS1IEJNMN5V8BI8svD664Y7s34yzZ5OZ3alXChecXUgC4qqZnAphHMNe4GuO7t0cqfJY4At5aMUm03QgQ5lGzg+5KytICJhU5MVAVf1Tu7B+Q4JzoPSQC2x7W5XVyQJy+wZUeUIDbGFpNLdjKrPq6sbjI8nz4OKcBIR1Jc9IGSraz4G/G7QT4D028NmWvNv22CF+ZYZF769/VmkLFYiKeWIYl/2K+eOGs/8FMDFU24tk+Nl6/9iXIJZ1eNKVAl+o/Ofr5zC7f9gwlQiMo7FKELavF3Sfj/xJToyiReXAoy7g3tB9Obzua5z30VY53MjkcoBRkQQ/zPT4v4ZLGYzPeTsczmgni98AGaFhyv+RpyYhBTAAaA+gWRgs4oIjLqPqJg+MzO3o="
  file_glob: true
  file: ./build/libs/SetupBuilder-*
  skip_cleanup: true
  overwrite: true
  on:
    repo: i-net-software/SetupBuilder
    tags: true
    condition: $DEPLOY = true
after_deploy:
  - ./gradlew publishPlugin
